/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 spiderman_2099.glb --transform 
Files: spiderman_2099.glb [6.47MB] > D:\NEW_Projects\portfolio\public\model\spiderman_2099-transformed.glb [2.24MB] (65%)
Author: realism (https://sketchfab.com/RealismModels)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spiderman-2099-e64be97744244b7db8bf039bdbc85d49
Title: Spiderman 2099
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/spiderman_2099-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials.hero_spiderman209901_S02_03} skeleton={nodes.Object_96.skeleton} />
        <skinnedMesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials.hero_spiderman209901_S02_04} skeleton={nodes.Object_98.skeleton} />
        <skinnedMesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.hero_spiderman209901_S02_02} skeleton={nodes.Object_100.skeleton} />
        <skinnedMesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials.hero_spiderman209901_S02_04} skeleton={nodes.Object_102.skeleton} />
        <skinnedMesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials.hero_spiderman209901_S02_01} skeleton={nodes.Object_104.skeleton} />
        <skinnedMesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials.SpiderMan_web02} skeleton={nodes.Object_106.skeleton} />
        <skinnedMesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials.SpiderMan_web02} skeleton={nodes.Object_108.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/spiderman_2099-transformed.glb')
