import type { Metadata } from "next";

import { MenuProvider } from "./context/MenuContext";
import Navbar from "./components/Navbar";
import CurvedNavbar from "./components/CurvedNavbar";
import SmoothScrollingWrapper from "@/utils/SmoothScrollingWrapper";
import SvgIcon from "./components/aboutComponents/SvgIcon";
import LayoutWrapper from "./components/LayoutWrapper";
import Head from "next/head";

import "./globals.css";
import { headers } from "next/headers";
import { NextRequest } from "next/server";
import { config } from "process";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,

}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <Head>
        <link
          rel="preload"
          href="/fonts/FKScreamerTrial-Bold-BF6571330a76e9b.otf"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
      </Head>
      <body className="bg-red-600">
        <SmoothScrollingWrapper>
          <MenuProvider>
            {/* <LayoutWrapper> */}
           

            {children}
            {/* </LayoutWrapper> */}
            {/* <Navbar /> */}
          </MenuProvider>
        </SmoothScrollingWrapper>
      </body>
    </html>
  );
}
