import type { Metadata } from "next";

import { MenuProvider } from "./context/MenuContext";

import SmoothScrollingWrapper from "@/utils/SmoothScrollingWrapper";
import SvgIcon from "./components/aboutComponents/SvgIcon";
import LayoutWrapper from "./components/LayoutWrapper";
import Head from "next/head";

import "./globals.css";

import { UserProvider } from "./context/UserContext";
import { ViewTransitions } from "next-view-transitions";
import ChatBubble from "./components/ChatBubble";
import { Toaster } from "sonner";
import ChatWrapper from "./components/ChatWrapper";
import { getUser } from "@/lib/user";
import UserChatInterface from "./components/chat/UserChatInterface";
import Preloader from "./components/Preloader";
import SlidingLogo, { SlidingLogoMarqueeItem } from "./components/SlidingLogo";
import { Github, Linkedin } from "lucide-react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const logos: SlidingLogoMarqueeItem[] = [
  {
    id: "1",
    content: <Github />,
    href: "https://github.com/Adnank999",
  },
  {
    id: "2",
    content: <Linkedin />,
    href: "https://www.linkedin.com/in/adnan-khan-9292971a6/",
  },
  {
    id: "3",
    content: <Github />,
    href: "https://github.com/Adnank999",
  },
  {
    id: "4",
    content: <Linkedin />,
    href: "https://www.linkedin.com/in/adnan-khan-9292971a6/",
  },
  {
    id: "5",
    content: <Github />,
    href: "https://github.com/Adnank999",
  },
  {
    id: "6",
    content: <Linkedin />,
    href: "https://www.linkedin.com/in/adnan-khan-9292971a6/",
  },
];
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user, role } = await getUser();
  return (
    <ViewTransitions>
      <html lang="en">
        <Head>
          <link
            rel="preload"
            href="/fonts/FKScreamerTrial-Bold-BF6571330a76e9b.otf"
            as="font"
            type="font/otf"
          />
        </Head>
        <body className="bg-red-600">
          <ViewTransitions>
            <SmoothScrollingWrapper>
              <LayoutWrapper>
                <MenuProvider>
                  <UserProvider user={user} role={role}>
                    {children}
                    <UserChatInterface />
                    <div className="max-w-2xl mx-auto w-full">
                      <SlidingLogo
                        items={logos}
                        speed={60}
                        height="120px"
                        enableBlur={true}
                        blurIntensity={2}
                        pauseOnHover={true}
                        showGridBackground={true}
                        // onItemClick={(item) => console.log("Clicked:", item.id)}
                      />
                    </div>
                    <Toaster position="top-right" />
                  </UserProvider>

                  {/* <Navbar /> */}
                </MenuProvider>
              </LayoutWrapper>
            </SmoothScrollingWrapper>
          </ViewTransitions>
        </body>
      </html>
    </ViewTransitions>
  );
}
