import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { MenuProvider } from "./context/MenuContext";
import Navbar from "./components/Navbar";
import CurvedNavbar from "./components/CurvedNavbar";
import SmoothScrollingWrapper from "@/utils/SmoothScrollingWrapper";
import SvgIcon from "./components/aboutComponents/SvgIcon";
import LayoutWrapper from "./components/LayoutWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="demotransition-5 ">
        <SmoothScrollingWrapper>
          <MenuProvider>
            <LayoutWrapper>
              <CurvedNavbar />

              {children}
            </LayoutWrapper>
            {/* <Navbar /> */}
          </MenuProvider>
        </SmoothScrollingWrapper>
      </body>
    </html>
  );
}
